name: Using Reuable Workflow
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules #~/.npm #we can use if condtion in all places where we used cache
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' #steps.IDName(cache).OuputOfPreviousStep(outputs).cache-hit
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        id: run-tests #This is added to refrence it later and step we are executing.
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure' #if asetp fails the other jobs will not be executed. failure() has to be used to ensure the the below executes along withthe condition
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy: #Here we are planning an entire workfloe to be resuse here
    needs: build
    uses:  ./.github/workflows/reusable.yml #pathofWorkflow #Here we do not reffer an action, but an entire workflow
    with:
      artifact-name: dist-files #Here what is defined in the previous step we are using it. As we do not want to use default as defined in reusable worflow.
    secrets:
      some-secret: {{ secrets.some-secret }}
  report: #To show if conditions work on job level. Previous was for steps
    needs: [lint, deploy] #If we wantthe job to run only if the following jobs failed, we need to apply needs commnds and steps
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Somthing went wrong"
          echo "{{ toJSON(github) }}"